# Generated by Django 6.0.4 on 2026-04-29 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_versions', to='dictionaries.dictionary')),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=300)),
                ('dictionary_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_items', to='dictionaries.dictionaryversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dictionaryversion',
            constraint=models.UniqueConstraint(fields=('dictionary', 'version'), name='unique_dictionary_version'),
        ),
        migrations.AddConstraint(
            model_name='dictionaryversion',
            constraint=models.UniqueConstraint(fields=('dictionary', 'start_date'), name='unique_dictionary_start_date'),
        ),
        migrations.AddConstraint(
            model_name='dictionaryitem',
            constraint=models.UniqueConstraint(fields=('dictionary_version', 'code'), name='unique_item_code_per_version'),
        ),
    ]
