# Generated by Django 6.0.4 on 2026-04-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name': 'Справочник', 'verbose_name_plural': 'Справочники'},
        ),
        migrations.AlterModelOptions(
            name='dictionaryitem',
            options={'verbose_name': 'Элемент справочника', 'verbose_name_plural': 'Элементы справочника'},
        ),
        migrations.AlterModelOptions(
            name='dictionaryversion',
            options={'verbose_name': 'Версия справочника', 'verbose_name_plural': 'Версии справочников'},
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dictionaryitem',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='dictionaryitem',
            name='value',
            field=models.CharField(max_length=300, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='dictionaryversion',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='dictionaryversion',
            name='version',
            field=models.CharField(max_length=50, verbose_name='Версия'),
        ),
    ]
