# Generated by Django 6.0.4 on 2026-04-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_alter_dictionary_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dictionaryversion',
            index=models.Index(fields=['dictionary', '-start_date'], name='dictionarie_diction_bd2fa8_idx'),
        ),
    ]
