# Generated by Django 6.0.4 on 2026-05-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_dictionaryversion_dictionarie_diction_bd2fa8_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dictionaryitem',
            index=models.Index(fields=['dictionary_version', 'code'], name='dictionarie_diction_516a12_idx'),
        ),
    ]
